name:                parac
version:             0.1.0.0
github:              "jmittert/parac"
license:             BSD3
author:              "Jason Mittertreiner"
maintainer:          "jason.mittertreiner@gmail.com"
copyright:           "None"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Undefined

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jmittert/parac#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fno-warn-name-shadowing
  dependencies:
    - containers
    - mtl
    - transformers
    - array
    - process
    - argparser
    - llvm-hs-pure == 6.0.0
    - llvm-hs
    - bytestring

executables:
  parac:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - parac
    - containers
    - process
    - argparser
    - bytestring

tests:
  parac-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-name-shadowing
    dependencies:
    - parac
    - process
    - hspec
    - hspec-core
    - QuickCheck
    - bytestring
